In [2]:
import numpy as np

In [3]:
# Criando uma matriz NumPy 2D a partir da sua lista original
vector_np = np.array([[1, 3, 5], [2, 4, 6], [7, 8, 9]])
print(f"Matriz NumPy:\n{vector_np} \n shape = {vector_np.shape}")

Matriz NumPy:
[[1 3 5]
 [2 4 6]
 [7 8 9]] 
 shape = (3, 3)


In [4]:
# Slicing to obtain all the values from the last columns
ultima_coluna_np = vector_np[2, :]
print(f"\nÚltima coluna:\n{ultima_coluna_np}")


Última coluna:
[7 8 9]


In [7]:
ultima_linha_np = vector_np[2, 2]
print(f"\nÚltima linha:\n{ultima_linha_np}")


Última linha:
9
