In [10]:
import numpy as np

In [11]:
# Criando uma matriz NumPy 2D a partir da sua lista original
vector_np = np.array([[1, 3, 5], [2, 4, 6], [7, 8, 9]])
print(f"Matriz NumPy:\n{vector_np}")

# Slicing para obter a última coluna
ultima_coluna_np = vector_np[:, 2]
print(f"\nÚltima coluna:\n{ultima_coluna_np}")

Matriz NumPy:
[[1 3 5]
 [2 4 6]
 [7 8 9]]

Última coluna:
[5 6 9]


In [ ]:
vector = [[1, 3, 5], [2, 4, 6], [7, 8, 9]]
print(f"First matrix 3x3 = {vector}")

In [ ]:
# lets slice!
print(f"Second row, third column, value = {vector[1][2]}")

print(f"It'll be a slice, showing all the values for the first row: {vector[0][:]}")

print(f"It'll also a slice, showing all the values of the last column: {vector[:][2]}")