In [1]:
import numpy as np

# Criando uma matriz NumPy 2D a partir da sua lista original
matriz = np.array([[1, 3, 5, 7, 9], [2, 4, 6, 8, 10], [70, 80, 90, 100, 110]])
print(f"Matriz NumPy:\n{matriz}")

Matriz NumPy:
[[  1   3   5   7   9]
 [  2   4   6   8  10]
 [ 70  80  90 100 110]]


In [13]:
linha_com_step_array = matriz[2, ::2]
print(linha_com_step_array)

[ 70  90 110]


In [2]:
odds_array_2 = matriz[1, 0:5:2]
print(odds_array_2)

[ 2  6 10]
