In [1]:
import numpy as np

In [2]:
array = np.arange(10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
# transform the previous array/list in a given n x n matrix
array_5x2 = array.reshape(5, 2)
print(array_5x2)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [7]:
# transform the previous array/list in a given n x n matrix
array_2x5 = array.reshape(2, 5)
print(array_2x5)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [17]:
array_unspecified = array.reshape(5, -1)
print(array_unspecified)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [19]:
array_unspecified = array.reshape(-1, 10)
print(array_unspecified)

[[0 1 2 3 4 5 6 7 8 9]]
