In [4]:
import numpy as np

mat_1 = np.array([[1,2], [3,4]])
mat_2 = np.array([[5,6]])

print(f"{mat_1} \n\n")
print(mat_2)

[[1 2]
 [3 4]] 


[[5 6]]


In [10]:
mat_2 = mat_2.reshape(2, -1)
print(f"mat_2 = \n{mat_2}\n\n")

concat = np.concatenate((mat_1, mat_2), axis=1)
print(f"Concat =\n {concat}")

mat_2 = 
[[5]
 [6]]


Concat =
 [[1 2 5]
 [3 4 6]]
